apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: asr
  name: asr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: asr
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  revisionHistoryLimit: 2
  template:
    metadata:
      labels:
        app: asr
    spec:
      containers:
      - image: beaware/asr:IMAGE_TAG
        imagePullPolicy: Always
        name: asr
        ports:
        - containerPort: 2087
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 200m
            memory: 2048Mi
        env:
          - name: SECRET_MH_API_KEY
            valueFrom:
             secretKeyRef:
              name: mh-secret2
              key: api_key
          - name: SECRET_MH_BROKERS
            valueFrom:
             secretKeyRef:
              name: mh-secret2
              key: kafka_brokers_sasl
          - name: SECRET_MONGO_URI
            valueFrom:
              secretKeyRef:
                name: mongo-bw2-secret
                key: uri  
